package seed

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/susamn/flashtui/internal/privilege"
)

// Mounted holds where the flashed partitions are currently mounted.
type Mounted struct {
	Boot string // may be empty for families without a boot partition
	Root string
}

// firstUID is the uid and gid the first user account gets on both Raspberry Pi
// OS and cloud images. Files are chowned to the number rather than the name
// because the account may not exist yet, or may be renamed on first boot.
const firstUID = "1000"

// Apply writes the seed configuration into the mounted filesystems.
//
// Everything is done by a single root shell script rather than by a series of
// privileged file writes, so the user authenticates once instead of once per
// file. The script is written with 0600 permissions and removed afterwards.
func Apply(ctx context.Context, esc *privilege.Escalator, det Detection, cfg Config, m Mounted, scratchDir string) error {
	if !det.Seedable() {
		return fmt.Errorf("cannot seed this image: %s", det.Reason)
	}
	if err := cfg.Validate(); err != nil {
		return err
	}
	if m.Root == "" {
		return fmt.Errorf("root filesystem is not mounted")
	}
	if det.Family == RaspberryPiOS && m.Boot == "" {
		return fmt.Errorf("boot partition is not mounted")
	}

	var hash string
	if cfg.Password != "" {
		h, err := hasher(ctx, cfg.Password)
		if err != nil {
			return err
		}
		hash = h
	}

	script, err := buildScript(det, cfg, m, hash)
	if err != nil {
		return err
	}

	// The script carries the password hash, so it must never be world
	// readable and must not outlive the call.
	path := filepath.Join(scratchDir, "flashtui-seed.sh")
	if err := os.WriteFile(path, []byte(script), 0o600); err != nil {
		return fmt.Errorf("stage seed script: %w", err)
	}
	defer os.Remove(path)

	cmd, err := esc.Command(ctx, "sh", path)
	if err != nil {
		return err
	}
	if out, err := cmd.CombinedOutput(); err != nil {
		if privilege.ErrDenied(err) {
			return fmt.Errorf("authorisation denied; the image was flashed but not configured")
		}
		return fmt.Errorf("seeding failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func buildScript(det Detection, cfg Config, m Mounted, hash string) (string, error) {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by flashtui. Runs once, as root, then is deleted.\n")
	b.WriteString("set -eu\n\n")
	fmt.Fprintf(&b, "ROOT=%s\n", shellQuote(m.Root))
	if m.Boot != "" {
		fmt.Fprintf(&b, "BOOT=%s\n", shellQuote(m.Boot))
	}
	b.WriteString("\n")

	switch det.Family {
	case RaspberryPiOS:
		writeRaspios(&b, cfg, hash)
	case CloudInit:
		writeCloudInit(&b, cfg, hash)
	default:
		return "", fmt.Errorf("no seeding routine for %s", det.Family)
	}

	b.WriteString("\nsync\n")
	return b.String(), nil
}

func writeRaspios(b *strings.Builder, cfg Config, hash string) {
	if cfg.EnableSSH {
		b.WriteString("# sshswitch.service enables sshd when this marker exists.\n")
		b.WriteString("touch \"$BOOT/ssh\"\n\n")
	}
	if hash != "" {
		b.WriteString("# userconfig.service consumes this, then runs\n")
		b.WriteString("# 'usermod -s /bin/bash', which is what unlocks the stock account:\n")
		b.WriteString("# it ships with /usr/sbin/nologin, so an SSH key alone is not enough.\n")
		fmt.Fprintf(b, "printf '%%s\\n' %s > \"$BOOT/userconf.txt\"\n",
			shellQuote(cfg.Username+":"+hash))
		b.WriteString("chmod 0600 \"$BOOT/userconf.txt\"\n\n")
	}
	if cfg.AuthorizedKey != "" {
		// The key goes to the stock account's home. When userconf renames the
		// user it runs 'usermod -m -d', which moves this directory along with
		// it, so seeding under the original name stays correct.
		b.WriteString("# Seeded under the stock home; userconf's 'usermod -m -d' moves it\n")
		b.WriteString("# if the account is renamed on first boot.\n")
		b.WriteString("HOME_DIR=\"$(awk -F: '$3==" + firstUID + "{print $6; exit}' \"$ROOT/etc/passwd\")\"\n")
		b.WriteString("[ -n \"$HOME_DIR\" ] || HOME_DIR=/home/" + cfg.Username + "\n")
		b.WriteString("SSH_DIR=\"$ROOT$HOME_DIR/.ssh\"\n")
		fmt.Fprintf(b, "install -d -m 0700 -o %s -g %s \"$SSH_DIR\"\n", firstUID, firstUID)
		fmt.Fprintf(b, "printf '%%s\\n' %s >> \"$SSH_DIR/authorized_keys\"\n", shellQuote(cfg.AuthorizedKey))
		fmt.Fprintf(b, "chmod 0600 \"$SSH_DIR/authorized_keys\"\n")
		fmt.Fprintf(b, "chown %s:%s \"$SSH_DIR/authorized_keys\"\n\n", firstUID, firstUID)
	}
	if cfg.Hostname != "" {
		writeHostname(b, cfg.Hostname)
	}
	if cfg.WifiSSID != "" {
		writeNetworkManagerWifi(b, cfg)
	}
}

func writeHostname(b *strings.Builder, host string) {
	fmt.Fprintf(b, "printf '%%s\\n' %s > \"$ROOT/etc/hostname\"\n", shellQuote(host))
	// /etc/hosts must resolve the new name or sudo stalls on every command
	// while it waits for the lookup to time out.
	b.WriteString("if [ -f \"$ROOT/etc/hosts\" ]; then\n")
	fmt.Fprintf(b, "  sed -i \"s/^127\\\\.0\\\\.1\\\\.1.*/127.0.1.1\\t%s/\" \"$ROOT/etc/hosts\"\n", host)
	fmt.Fprintf(b, "  grep -q '^127\\.0\\.1\\.1' \"$ROOT/etc/hosts\" || printf '127.0.1.1\\t%%s\\n' %s >> \"$ROOT/etc/hosts\"\n", shellQuote(host))
	b.WriteString("fi\n\n")
}

// writeNetworkManagerWifi writes a keyfile connection. Raspberry Pi OS has used
// NetworkManager since Bookworm, so wpa_supplicant.conf is no longer read.
func writeNetworkManagerWifi(b *strings.Builder, cfg Config) {
	profile := fmt.Sprintf(`[connection]
id=%s
type=wifi
autoconnect=true

[wifi]
mode=infrastructure
ssid=%s

[wifi-security]
key-mgmt=wpa-psk
psk=%s

[ipv4]
method=auto

[ipv6]
method=auto
`, cfg.WifiSSID, cfg.WifiSSID, cfg.WifiPSK)

	b.WriteString("# NetworkManager keyfile; it refuses any profile that is not 0600.\n")
	b.WriteString("NM_DIR=\"$ROOT/etc/NetworkManager/system-connections\"\n")
	b.WriteString("install -d -m 0755 \"$NM_DIR\"\n")
	fmt.Fprintf(b, "printf '%%s' %s > \"$NM_DIR/%s.nmconnection\"\n", shellQuote(profile), sanitizeFilename(cfg.WifiSSID))
	fmt.Fprintf(b, "chmod 0600 \"$NM_DIR/%s.nmconnection\"\n", sanitizeFilename(cfg.WifiSSID))
	// The regulatory domain gates which channels the radio may use; without it
	// the 5 GHz band stays disabled on a Pi.
	fmt.Fprintf(b, "printf 'REGDOMAIN=%%s\\n' %s > \"$ROOT/etc/default/crda\" 2>/dev/null || true\n\n",
		shellQuote(strings.ToUpper(cfg.WifiCountry)))
}

func writeCloudInit(b *strings.Builder, cfg Config, hash string) {
	var ud strings.Builder
	ud.WriteString("#cloud-config\n")
	if cfg.Hostname != "" {
		fmt.Fprintf(&ud, "hostname: %s\n", yamlString(cfg.Hostname))
		ud.WriteString("preserve_hostname: false\n")
	}
	ud.WriteString("users:\n")
	fmt.Fprintf(&ud, "  - name: %s\n", yamlString(cfg.Username))
	ud.WriteString("    shell: /bin/bash\n")
	ud.WriteString("    sudo: 'ALL=(ALL) NOPASSWD:ALL'\n")
	ud.WriteString("    groups: [adm, sudo]\n")
	if hash != "" {
		ud.WriteString("    lock_passwd: false\n")
		fmt.Fprintf(&ud, "    passwd: %s\n", yamlString(hash))
	}
	if cfg.AuthorizedKey != "" {
		ud.WriteString("    ssh_authorized_keys:\n")
		fmt.Fprintf(&ud, "      - %s\n", yamlString(cfg.AuthorizedKey))
	}
	if hash != "" {
		ud.WriteString("ssh_pwauth: true\n")
	}
	if cfg.EnableSSH {
		ud.WriteString("runcmd:\n")
		ud.WriteString("  - [systemctl, enable, --now, ssh]\n")
	}

	b.WriteString("# NoCloud seed. cloud-init reads this directory on first boot,\n")
	b.WriteString("# which avoids having to add a 'cidata' partition to the device.\n")
	b.WriteString("SEED=\"$ROOT/var/lib/cloud/seed/nocloud-net\"\n")
	b.WriteString("install -d -m 0755 \"$SEED\"\n")
	fmt.Fprintf(b, "printf '%%s' %s > \"$SEED/user-data\"\n", shellQuote(ud.String()))
	// meta-data must exist, even empty, or the NoCloud datasource skips the
	// directory entirely.
	fmt.Fprintf(b, "printf '%%s\\n' %s > \"$SEED/meta-data\"\n",
		shellQuote("instance-id: flashtui-"+cfg.Username))
	b.WriteString("chmod 0600 \"$SEED/user-data\"\n")
	// A previous boot of the same image would otherwise make cloud-init skip
	// the new seed as already applied.
	b.WriteString("rm -rf \"$ROOT/var/lib/cloud/instance\" \"$ROOT/var/lib/cloud/instances\" 2>/dev/null || true\n")
}

// shellQuote renders s as a single-quoted shell word, which is literal for
// every byte except the quote itself.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// yamlString renders s as a double-quoted YAML scalar, so a hash full of $ and
// / or a key with a comment cannot be reinterpreted as YAML syntax.
func yamlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`)
	return `"` + r.Replace(s) + `"`
}

// sanitizeFilename keeps an SSID usable as a filename without letting it escape
// the directory.
func sanitizeFilename(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "wifi"
	}
	return b.String()
}
